### ISSUE TITLE
Copy content from existing website to WordPress

### ISSUE THREAD

**Issue by zachgharst** [pkiuna/Web-Development-1--Transportation-Logistics#4]

**Comment by Bobbyjuba** [comment]
Pages with quotes need the quotes separated onto the right side of the page... Not sure how to achieve this design. Most of the site's photos should be switched to inline photos, but this cannot be done until uploading photos is allowed. Galleries should be implemented on the Over The Road, Our Fleet, and Freight pages, but this also cannot be done until uploading photos is allowed. I think the site is in an acceptable state for a prototype.
